### ISSUE TITLE
nvim-treesitter[gomod]: Error during tarball extraction.  tar: Error opening archive: Failed to open 'tree-sitter-gomod.tar.gz' 

### ISSUE THREAD

**Issue by CrazyCatZhang** [abzcoding/lvim#141]
Such as title

**Comment by abzcoding** [comment]
it is a treesitter or local issue, not related to this config

look through these to find the root cause:

https://github.com/LunarVim/LunarVim/issues/1578#issuecomment-1758029585
https://github.com/nvim-treesitter/nvim-treesitter/issues/4250
https://github.com/nvim-treesitter/nvim-treesitter/issues/4051
https://github.com/nvim-treesitter/nvim-treesitter/issues?q=is%3Aissue+%22tarball+extraction%22
