### ISSUE TITLE
module `catppuccin` not found

### ISSUE THREAD

**Issue by Suyashtnt** [abzcoding/lvim#59]
When I try to switch the colour scheme to `catppuccin`, it just gives me a massive error
![image](https://user-images.githubusercontent.com/45307955/173144766-96a5f695-721f-4982-a43c-88f662ce0313.png)

**Comment by abzcoding** [comment]
yes, changing the theme is not that easy 😅 (sorry for that)
since I have time-based themes

<img width="525" alt="Screen Shot 2022-06-11 at 12 54 16 AM" src="https://user-images.githubusercontent.com/10992695/173145026-92f80378-67e4-437b-b224-ea82616ee977.png">



i would suggest forking my repo and not using it directly
then you can change these lines
https://github.com/abzcoding/lvim/blob/4e862d6412b37be06eac761c37b23afd539c5d95/lua/user/plugins.lua#L9-L28

and also these
https://github.com/abzcoding/lvim/blob/4e862d6412b37be06eac761c37b23afd539c5d95/lua/user/theme.lua#L243-L263

**Comment by Suyashtnt** [comment]
> yes, changing the theme is not that easy sweat_smile (sorry for that) since I have time-based themes
> 
> <img alt="Screen Shot 2022-06-11 at 12 54 16 AM" width="525" src="https://user-images.githubusercontent.com/10992695/173145026-92f80378-67e4-437b-b224-ea82616ee977.png">
> 
> i would suggest forking my repo and not using it directly then you can change these lines
> 
> https://github.com/abzcoding/lvim/blob/4e862d6412b37be06eac761c37b23afd539c5d95/lua/user/plugins.lua#L9-L55
> 
> and also these
> 
> https://github.com/abzcoding/lvim/blob/4e862d6412b37be06eac761c37b23afd539c5d95/lua/user/theme.lua#L243-L256

If you check my GH i do have a personal fork, thanks for the info!

**Comment by abzcoding** [comment]
> If you check my GH i do have a personal fork, thanks for the info!

good so to be clear
you cannot just do `:colorscheme catppuccin` with your current codebase ( you'll get that error thingy

you have to either 
- change the time tables
- or remove them entirely and use a single theme

**Comment by luxus** [comment]
@Suyashtnt good news, abz added a easier way to change the theme

**Comment by Suyashtnt** [comment]
> @Suyashtnt good news, abz added a easier way to change the theme

I no longer use abzcoding, but if I go back to it then thanks for letting me know
