### ISSUE TITLE
jdtls could't resolve awt or graalvm

### ISSUE THREAD

**Issue by eihqnh** [abzcoding/lvim#74]
I m using graalvm and did't set
filteredTypes

![Screenshot_20220817_160919.jpg](https://user-images.githubusercontent.com/40905037/185089155-63d67bbd-8c25-4584-8bcb-77b82899653e.jpg)

**Comment by eihqnh** [comment]
> read this -> https://github.com/redhat-developer/vscode-java/pull/1196#issuecomment-568192224
> 
> 
> And watch [this video](https://www.youtube.com/watch?v=0q_MKUynUck) to get a sense of how nvim-jdtls works 

Thank you for replying
I'm a little confused why Lunar's lsp installer can load awt by default？

**Comment by abzcoding** [comment]
> > read this -> [redhat-developer/vscode-java#1196 (comment)](https://github.com/redhat-developer/vscode-java/pull/1196#issuecomment-568192224)
> > And watch [this video](https://www.youtube.com/watch?v=0q_MKUynUck) to get a sense of how nvim-jdtls works
> 
> Thank you for replying I'm a little confused why Lunar's lsp installer can load awt by default？

it doesn't have anything to do with Lunarvim 😅 
it is mostly related to [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) plugin and the way java projects work on neovim
since i'm not a java developer, i just linked you a video and a comment that would explain how does nvim-jdtls works
and also how can you use it on standalone projects that doesn't use maven
